# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aradhana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Class 1-4', 'Class 1 to 4'), ('Class 5-7', 'Class 5 to 7'), ('Class 8-10', 'Class 8 to 10')], default='Select', max_length=100),
        ),
    ]
